import { NextPage } from 'next';
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import Link from 'next/link';
import { ReactNode } from 'react';
import { Container, Nav, NavItem } from 'reactstrap';

interface Props {
  children: ReactNode;
}

const Layout: NextPage<Props> = ({ children }) => {
  const { data: session, status } = useSession();

  return (
    <div>
      <Head>
        <title>Money Allocation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Nav className="navbar navbar-dark bg-dark">
          <NavItem>
            <Link className="navbar-brand" href="/">
              ホーム
            </Link>
          </NavItem>
          <NavItem className="ml-auto">
            <Link className="navbar-brand" href="/">
              Link1
            </Link>
          </NavItem>
          <NavItem
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            {status === 'authenticated' ? (
              <Link className="navbar-brand" href="/">
                {session.user?.name}
              </Link>
            ) : (
              <Link className="navbar-brand" href="/">
                ログイン
              </Link>
            )}
          </NavItem>
        </Nav>
      </header>
      <Container style={{ marginTop: 50 }}>{children}</Container>
    </div>
  );
};

export default Layout;
